openapi: '3.0.2'
info:
  title: Bank Account Management API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /accounts:
    get:
      summary: Get all accounts
      tags:
        - Accounts
      responses:
        '200':
          description: List of all accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
  /accounts/{Id}:
    get:
      summary: Get account by ID
      tags:
        - Accounts
      parameters:
        - name: accountId
          in: path
          description: ID of the account to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Account details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
    post:
      summary: Create a new account
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

  /balances:
    get:
      summary: Get current balance or balance history
      tags:
        - Balances
      parameters:
        - name: date
          in: query
          description: Date for which balance is requested (YYYY-MM-DD format)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Success - Balance retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BalanceSnapshot'

  /withdrawal:
    post:
      summary: Perform a money withdrawal
      tags:
        - Withdrawals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawalRequest'
      responses:
        '200':
          description: Success - Withdrawal performed successfully

  /deposits:
    post:
      summary: Make a deposit into the account
      tags:
        - Deposits
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        '200':
          description: Success - Deposit made successfully

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the account
        name:
          type: string
          description: Last name of the client
        firstName:
          type: string
          description: First name(s) of the client
        birthday:
          type: string
          format: date
          description: Client's date of birth (in YYYY-MM-DD format)
        monthlySalary:
          type: number
          description: Client's monthly net salary
        accountNumber:
          type: string
          description: Unique account number
        overdraft_enabled:
          type: boolean
          description: Indicates if overdraft option is enabled for the account
        overdraft_limit:
          type: number
          description: Maximum overdraft limit allowed
        interest_rate_first_7_days:
          type: number
          description: Interest rate for the first 7 days of overdraft
        interest_rate_subsequent_days:
          type: number
          description: Interest rate for subsequent days of overdraft

    BalanceSnapshot:
      type: object
      properties:
        date:
          type: string
          format: date
          description: Date for which balance snapshot is recorded
        main_balance:
          type: number
          description: Principal balance available in the account
        loan_balance:
          type: number
          description: Amount borrowed from the bank (if overdraft is enabled)
        loan_interest:
          type: number
          description: Interest accrued on borrowed amount

    WithdrawalRequest:
      type: object
      properties:
        account_id:
          type: string
          description: Account identifier
        withdrawal_amount:
          type: number
          description: Amount to withdraw
        withdrawal_datetime:
          type: string
          format: date-time
          description: Date and time of the withdrawal
      required:
        - account_id
        - withdrawal_amount
        - withdrawal_datetime

    DepositRequest:
      type: object
      properties:
        amount:
          type: number
          description: Amount to deposit
        source:
          type: string
          description: Source of the deposit (external bank, internal account)
        reason:
          type: string
          description: Reason for the deposit
        effective_date:
          type: string
          format: date
          description: Date when the deposit will take effect
        registration_date:
          type: string
          format: date
          description: Date when the deposit is recorded
      required:
        - amount
        - source
        - effective_date