openapi: '3.0.2'
info:
  title: Bank Account Management API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /accounts:
    get:
      summary: Get all accounts
      tags:
        - Accounts
      responses:
        '200':
          description: List of all accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /accounts/{Id}:
    get:
      summary: Get account by ID
      tags:
        - Accounts
      parameters:
        - name: accountId
          in: path
          description: ID of the account to retrieve
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Account details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create a new account
      tags:
        - Accounts
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /balances:
    get:
      summary: Get current balance or balance history
      tags:
        - Balances
      parameters:
        - name: date
          in: query
          description: Date for which balance is requested (YYYY-MM-DD format)
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Success - Balance retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BalanceSnapshot'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /withdrawal:
    post:
      summary: Perform a money withdrawal
      tags:
        - Withdrawals
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawalRequest'
      responses:
        '200':
          description: Success - Withdrawal performed successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /deposits:
    post:
      summary: Make a deposit into the account
      tags:
        - Deposits
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        '200':
          description: Success - Deposit made successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /transfers:
    get:
      summary: Get all transfers
      tags:
        - Transfers
      responses:
        '200':
          description: List of all transfers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /transfers/{id}:
    get:
      summary: Get transfer by ID
      tags:
        - Transfers
      parameters:
        - name: id
          in: path
          description: ID of the transfer to retrieve
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Transfer details retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

    post:
      summary: Create a new transfer
      tags:
        - Transfers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transfer'
      responses:
        '200':
          description: Transfer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /statements:
    get:
      summary: Get account statements
      tags:
        - Statements
      parameters:
        - name: start_date
          in: query
          description: Start date of the statement period (YYYY-MM-DD format)
          required: true
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          description: End date of the statement period (YYYY-MM-DD format)
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Account statements retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountStatement'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the account
        name:
          type: string
          description: Last name of the client
        firstName:
          type: string
          description: First name(s) of the client
        birthday:
          type: string
          format: date
          description: Client's date of birth (in YYYY-MM-DD format)
        monthlySalary:
          type: number
          description: Client's monthly net salary
        accountNumber:
          type: string
          description: Unique account number
        overdraft_enabled:
          type: boolean
          description: Indicates if overdraft option is enabled for the account
        overdraft_limit:
          type: number
          description: Maximum overdraft limit allowed
        interest_rate_first_7_days:
          type: number
          description: Interest rate for the first 7 days of overdraft
        interest_rate_subsequent_days:
          type: number
          description: Interest rate for subsequent days of overdraft

    BalanceSnapshot:
      type: object
      properties:
        date:
          type: string
          format: date
          description: Date for which balance snapshot is recorded
        main_balance:
          type: number
          description: Principal balance available in the account
        loan_balance:
          type: number
          description: Amount borrowed from the bank (if overdraft is enabled)
        loan_interest:
          type: number
          description: Interest accrued on borrowed amount

    WithdrawalRequest:
      type: object
      properties:
        account_id:
          type: string
          description: Account identifier
        withdrawal_amount:
          type: number
          description: Amount to withdraw
        withdrawal_datetime:
          type: string
          format: date-time
          description: Date and time of the withdrawal
      required:
        - account_id
        - withdrawal_amount
        - withdrawal_datetime

    DepositRequest:
      type: object
      properties:
        amount:
          type: number
          description: Amount to deposit
        source:
          type: string
          description: Source of the deposit (external bank, internal account)
        reason:
          type: string
          description: Reason for the deposit
        effective_date:
          type: string
          format: date
          description: Date when the deposit will take effect
        registration_date:
          type: string
          format: date
          description: Date when the deposit is recorded
      required:
        - amount
        - source
        - effective_date

    Transfer:
      type: object
      properties:
        id:
          type: integer
          description: Unique identifier of the transfer
        sender_account_id:
          type: integer
          description: ID of the sender account
        receiver_account_id:
          type: integer
          description: ID of the receiver account
        amount:
          type: number
          description: Amount of the transfer
        reason:
          type: string
          description: Reason for the transfer
        initiation_date:
          type: string
          format: date-time
          description: Date and time when the transfer was initiated
        scheduled_date:
          type: string
          format: date-time
          description: Date and time when the transfer is scheduled to occur
        status:
          type: string
          enum: [Initiated, Pending, Completed, Cancelled]
          description: Status of the transfer
      required:
        - sender_account_id
        - receiver_account_id
        - amount
        - reason
        - initiation_date
        - status

    AccountStatement:
      type: object
      properties:
        operation_type:
          type: string
          description: Type of operation (credit or debit)
        operation_date:
          type: string
          format: date-time
          description: Date and time of the operation
        amount:
          type: number
          description: Amount of the operation
        operation_description:
          type: string
          description: Description or reason for the operation
        main_balance:
          type: number
          description: Main balance at the time of the operation
      required:
        - operation_type
        - operation_date
        - amount
        - operation_description
        - main_balance

  responses:

    BadRequest:
      description: The request parameters are invalid or missing.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: The request parameters are invalid or missing.

    NotFound:
      description: The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: The requested resource was not found.

    InternalServerError:
      description: An unexpected error occurred on the server.
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                description: An unexpected error occurred on the server.